### ISSUE TITLE
升级 pip 到 22.3 后出错

### ISSUE THREAD

**Issue by hongqn** [timfeirg/lain-cli#73]
升级 pip 到 22.3 后，运行 lain 出错。降级到 22.2.2 后正常。

```
❯ lain init
not in a lain app repo
please use --commit, otherwise you'll have to git add / commit by hand
lain lint --simple
Traceback (most recent call last):
  File "/Users/hongqn/.virtualenvs/lain-cli/bin/lain", line 8, in <module>
    sys.exit(main())
  File "/Users/hongqn/p/lain-cli/lain_cli/lain.py", line 2433, in main
    lain(obj={})
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hongqn/.virtualenvs/lain-cli/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/hongqn/p/lain-cli/lain_cli/lain.py", line 187, in lain
    version_challenge()
  File "/Users/hongqn/p/lain-cli/lain_cli/utils.py", line 2856, in version_challenge
    search_scope = SearchScope.create(find_links=[], index_urls=[pypi_index])
TypeError: SearchScope.create() missing 1 required positional argument: 'no_index'
```

**Comment by Linusp** [comment]
我也遇到了 :joy:
